# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: hellschwarz
description: > # this means to ignore newlines until "baseurl:"
  a keyboard mercenary
baseurl: https://hermann-p.github.io  # the subpath of your site, e.g. /blog
url: https://hermann-p.github.io/  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: standard  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: hellschwarz
email: waechtertroll@web.de

navigation:
  - text: Home
    url: /
  - text: Blog
    url: blog
#   - text: Docs
#     url: docs
  - text: Projects
    url: examples

projects:
  - name: pressspan
    description: Tool to find, filter and visualize complex splicing events from `segemehl` output
    link: https://github.com/hermann-p/pressspan
  - name: Das Rezeptbuch
    description: RESTful server for our family cooking recipes with responsive, reactive web frontend
    link: https://github.com/hermann-p/recipes
  - name: Noodles+
    description: >
      Code framework for the HTML5/ClojureScript/Pixi.js puzzle game,
      designed for mobile devices, published by Estraneo Labs
    link: waechtertroll.lima-city.de/noodles-nosound
#   - name: git-secret
#     description: A bash-tool to store your private data inside a git repository.
#     link: https://sobolevn.github.io/git-secret
#     image: https://github.com/sobolevn/git-secret/blob/7c9ae0b1853d4c15549027524121b9e40219fe47/images/git-secret-sm.png?raw=true

social:
  - service: github
    username: hermann-p
    link: https://github.com/hermann-p

# Plugins
gems:
  - jekyll-seo-tag
